
# Use an official Python runtime as base image for the backend
FROM python:latest AS backend

# Set working directory for the backend
WORKDIR /app/backend

# Copy requirements.txt to the working directory
COPY ./requirements.txt .

# Install backend dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the backend code to the working directory
COPY . .

# Expose the ports
EXPOSE 3000 8000

# Command to run the combined application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
